import { chromium as playwright } from '@playwright/test';
import chromium from '@sparticuz/chromium';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { brotliDecompressSync } from 'node:zlib';
import { execFileSync } from 'node:child_process';
const libs = path.join(os.tmpdir(), 'astra-browser-libs');
await fs.mkdir(libs, { recursive: true });
const tar = path.join(libs, 'libraries.tar');
await fs.writeFile(tar, brotliDecompressSync(await fs.readFile('/home/user/dnd-astra/node_modules/@sparticuz/chromium/bin/al2023.tar.br')));
execFileSync('tar', ['-xf', tar, '-C', libs]);
const browser = await playwright.launch({ executablePath: await chromium.executablePath(), args: chromium.args.filter(a => !['--single-process','--in-process-gpu'].includes(a)), env: { ...process.env, LD_LIBRARY_PATH: `${path.join(libs,'lib')}:${process.env.LD_LIBRARY_PATH??''}` }, headless: true });
const page = await browser.newPage({ viewport: { width: 1000, height: 640 } });
page.setDefaultTimeout(240000);
const quality = process.env.ASTRA_QUALITY ?? 'high';
await page.addInitScript(q => localStorage.setItem('astra-preferences-v1', JSON.stringify({ quality: q, atmosphere: 'golden', volume: 0, sensitivity: 1, invertY: false })), quality);
const t0 = Date.now();
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' });
await page.waitForSelector('#enter-world:visible');
await page.click('#enter-world');
await page.waitForSelector('#char-creation:visible');
await page.click('[data-recommended]');
await page.click('[data-review]');
await page.waitForSelector('[data-forge]:visible');
await page.click('[data-forge]');
await page.waitForSelector('[data-ready="true"]', { timeout: 240000 });
console.log('ready in', ((Date.now() - t0) / 1000).toFixed(1), 's');
await page.click('#journey-skip');
await page.waitForFunction(() => window.__astra.getState().story.phase === 'arrival');
for (let i = 0; i < 4; i++) { await page.click('#narrator-next').catch(() => {}); await page.waitForTimeout(200); }
await page.keyboard.press('r');
await page.waitForFunction(() => !window.__astra.getState().mounted, { timeout: 30000 });
await page.evaluate(() => window.__astra.teleport(2, 6));
await page.waitForTimeout(1200);
const diag = await page.evaluate(() => window.__astra.getDiagnostics());
console.log('draw calls', diag.calls, 'triangles', diag.triangles, 'trees', diag.trees, 'quality', diag.quality);
const fps = await page.evaluate(() => new Promise(res => { let n = 0; const t = performance.now(); const loop = () => { n++; if (performance.now() - t < 3000) requestAnimationFrame(loop); else res((n / 3).toFixed(1)); }; requestAnimationFrame(loop); }));
console.log('approx fps (headless swiftshader):', fps);
await browser.close();
