import { chromium as playwright } from '@playwright/test';
import chromium from '@sparticuz/chromium';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { brotliDecompressSync } from 'node:zlib';
import { execFileSync } from 'node:child_process';
const libs = path.join(os.tmpdir(), 'astra-browser-libs'); await fs.mkdir(libs, { recursive: true });
const tar = path.join(libs, 'libraries.tar');
await fs.writeFile(tar, brotliDecompressSync(await fs.readFile('node_modules/@sparticuz/chromium/bin/al2023.tar.br'))); execFileSync('tar', ['-xf', tar, '-C', libs]);
const browser = await playwright.launch({ executablePath: await chromium.executablePath(), args: chromium.args.filter(a => !['--single-process', '--in-process-gpu'].includes(a)), env: { ...process.env, LD_LIBRARY_PATH: `${path.join(libs, 'lib')}:${process.env.LD_LIBRARY_PATH ?? ''}` }, headless: true });
const page = await browser.newPage({ viewport: { width: 1000, height: 700 }, deviceScaleFactor: 1 }); page.setDefaultTimeout(90000);
const errors = [], failed = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error' && !m.text().toLowerCase().includes('pointer lock')) errors.push(m.text()); });
page.on('requestfailed', r => failed.push(r.url()));
await page.addInitScript(() => localStorage.setItem('astra-preferences-v1', JSON.stringify({ quality: 'performance', atmosphere: 'golden', volume: .35, sensitivity: 1, invertY: false })));
const state = () => page.evaluate(() => window.__astra.getState());
const inventory = () => page.evaluate(() => window.__astra.getInventory());
const character = () => page.evaluate(() => window.__astra.getCharacter());
const wait = predicate => page.waitForFunction(predicate, undefined, { timeout: 90000, polling: 100 });
try {
  await page.goto(process.env.BASE_URL ?? 'http://localhost:5173', { waitUntil: 'domcontentloaded' });
  // Title first: the world only loads once the player presses Begin.
  await page.waitForSelector('#enter-world:visible');
  assert.equal(await page.locator('#char-creation').count(), 0);
  console.log('✓ Title opens before the world loads');
  // FORGE YOUR LEGEND gates entry: Begin opens creation; the world loads behind it.
  await page.click('#enter-world');
  await page.waitForSelector('#char-creation:visible');
  await page.click('[data-recommended]');
  assert.equal(await page.locator('[data-review]').isDisabled(), false);
  await page.click('[data-review]');
  await page.waitForSelector('[data-forge]:visible');
  await page.click('[data-forge]');
  await page.waitForSelector('#char-creation', { state: 'detached' });
  await page.waitForSelector('[data-ready="true"]', { timeout: 180000 });
  await page.waitForSelector('#loading', { state: 'detached' });
  const hero = await character();
  assert(hero && hero.name.length >= 2); assert.equal(hero.class, 'Fighter'); assert.equal(hero.hp.current, hero.hp.max);
  await page.waitForSelector('#hero-plate:visible');
  console.log('✓ Character creation forges a level-1 Fighter and lights the hero plate');
  await wait(() => window.__astra.getState().story.active);
  assert.equal((await state()).story.phase, 'journey'); assert((await page.locator('#narrator-text').textContent()).startsWith('You began your adventuring career in the city of Neverwinter.'));
  assert.equal((await state()).mounted, true); assert.equal((await inventory()).gold, 0);
  assert.equal(await page.locator('[data-view="first"]').isDisabled(), true);
  // The forge→load gap can outlive autoplay activation; any gesture restores voice.
  await page.keyboard.press('Shift');
  await wait(() => window.__astra.getState().story.fallback === false);
  await wait(() => window.__astra.getState().story.progress > .025);
  assert.equal((await state()).story.fallback, false);
  await page.click('#narrator-pause'); const progress = (await state()).story.progress;
  await page.waitForTimeout(400); assert(Math.abs((await state()).story.progress - progress) < .002);
  console.log('✓ Narrator uses real audio, exact text, cinematic input lock, and synchronized pause');
  await page.click('#journey-skip'); await wait(() => window.__astra.getState().story.phase === 'arrival');
  assert.equal((await state()).mounted, true); assert.equal((await inventory()).arrived, true);
  assert((await page.locator('#narrator-text').textContent()).startsWith("You've been on the Triboar Trail for about half a day"));
  await page.click('#narrator-pause');
  const beforeDrive = (await state()).wagon.x;
  await page.keyboard.down('w');
  await page.waitForFunction(x => window.__astra.getState().wagon.x > x + .25, beforeDrive, { timeout: 90000, polling: 100 });
  await page.keyboard.up('w'); await page.keyboard.down('Space'); await page.waitForTimeout(500); await page.keyboard.up('Space');
  assert((await state()).wagon.x > beforeDrive);
  console.log('✓ Skipping hands control back, starts arrival narration, and the wagon can be driven');
  await page.click('#narrator-next'); await page.click('#narrator-next'); await wait(() => window.__astra.getState().story.phase === 'exploration');
  await page.keyboard.press('r'); await wait(() => !window.__astra.getState().mounted);
  await page.keyboard.press('e'); await page.waitForSelector('[data-kind="cargo"]');
  assert.equal(await page.locator('#dialog-title').innerText(), 'The oil barrel');
  await page.locator('[data-loot-quantity="oil"]').fill('3'); await page.click('[data-take-item="oil"]');
  assert.equal((await inventory()).inventory.oil, 3); assert.equal((await inventory()).cargo.oil.oil, 47); assert.equal((await inventory()).gold, 0);
  await page.click('[data-action="take-all"]'); assert.equal((await inventory()).inventory.oil, 50);
  assert.equal(await page.locator('[data-action="take-all"]').isDisabled(), true);
  await page.keyboard.press('i'); await page.waitForSelector('[data-kind="inventory"]');
  assert.equal(await page.locator('#purse-gold').innerText(), '0'); assert((await page.locator('#item-detail').innerText()).includes('0.10 gp'));
  await page.locator('#inventory-search').fill('shovel'); assert((await page.locator('#inventory-list').innerText()).includes('Nothing on this page'));
  await page.locator('#inventory-search').fill('oil'); assert((await page.locator('#inventory-list').innerText()).includes('Lantern oil'));
  await page.keyboard.press('Escape');
  console.log('✓ Dismount, opening, partial/all looting, decimal gp, inventory search, and no duplicate oil');
  // Walk along the wagon, not a test-only teleport, to reach an actual wooden flour crate.
  const footStart = await state(); await page.keyboard.down('s');
  await page.waitForFunction(start => {
    const p = window.__astra.getState(); return Math.hypot(p.x - start.x, p.z - start.z) > 1.8;
  }, footStart, { timeout: 90000, polling: 100 }); await page.keyboard.up('s');
  await wait(() => window.__astra.getState().interaction?.kind === 'cargo' && window.__astra.getState().interaction.id.startsWith('flour'));
  await page.keyboard.press('e'); await page.waitForSelector('[data-kind="cargo"]'); assert((await page.locator('#dialog-title').innerText()).includes('Flour crate'));
  await page.click('[data-action="take-all"]'); assert.equal((await inventory()).inventory.flour, 6);
  await page.keyboard.press('Escape');
  console.log('✓ Walking reaches a wooden crate; opening it transfers its six flour sacks');
  await page.keyboard.press('Space'); await wait(() => !window.__astra.getState().grounded); await wait(() => window.__astra.getState().grounded);
  await page.keyboard.press('v'); await wait(() => window.__astra.getState().mode === 'first'); await page.keyboard.press('v'); await wait(() => window.__astra.getState().mode === 'third');
  await page.keyboard.press('m'); await page.waitForSelector('[data-kind="map"]'); assert.equal((await state()).paused, true);
  await page.keyboard.press('m'); await page.waitForSelector('#dialog-backdrop', { state: 'hidden' });
  await page.keyboard.press('n'); await page.waitForSelector('[data-kind="journal"]'); assert((await page.locator('.journal-scroll').innerText()).includes('Two horses wander the road, sniffing at ransacked personal effects.'));
  await page.keyboard.press('Escape');
  console.log('✓ Jump/landing, both camera modes, live map, and the complete story journal work');
  // Character sheet (C) and the camp menu (pause-menu rest shortcut path).
  await page.keyboard.press('c'); await page.waitForSelector('[data-kind="sheet"]');
  assert((await page.locator('#dialog').innerText()).includes('LEVEL 1 HUMAN FIGHTER'));
  assert((await page.locator('#dialog').innerText()).includes('Second Wind'));
  await page.keyboard.press('Escape');
  await page.evaluate(() => window.__astra.openCamp());
  await page.waitForSelector('#camp-menu.visible');
  assert((await page.locator('#camp-menu').innerText()).includes('LONG REST'));
  assert((await page.locator('#camp-menu').innerText()).includes('SHORT REST'));
  await page.click('[data-camp="close"]');
  await page.waitForSelector('#camp-menu', { state: 'hidden' });
  console.log('✓ Character sheet and the make-camp menu open over the live world');
  await page.click('#settings-toggle');
  await page.click('[data-weather="rain"]'); assert.equal(await page.locator('[data-weather="rain"]').getAttribute('aria-pressed'), 'true');
  await page.click('[data-weather="auto"]'); assert.equal(await page.locator('[data-weather="auto"]').getAttribute('aria-pressed'), 'true');
  await page.locator('#sensitivity').fill('1.3'); assert.equal(await page.locator('#sensitivity-value').innerText(), '1.3×');
  await page.click('[data-action="audio"]'); assert.equal(await page.locator('[data-action="audio"]').getAttribute('aria-checked'), 'true'); await page.click('[data-action="audio"]');
  await page.click('[data-action="narrator-voice"]'); assert.equal(await page.locator('[data-action="narrator-voice"]').getAttribute('aria-checked'), 'false'); await page.click('[data-action="narrator-voice"]');
  await page.click('[data-action="close"]');
  await page.keyboard.press('h'); await page.waitForSelector('[data-kind="help"]'); await page.keyboard.press('Escape');
  await page.keyboard.press('p'); const photo = page.waitForEvent('download', { timeout: 120000 }); await page.click('#capture-photo'); assert((await photo).suggestedFilename().startsWith('astra-triboar-trail-')); await page.click('#exit-photo');
  console.log('✓ Weather, settings, separate voice/ambience controls, help, and PNG capture work');
  const beforeReload = await inventory();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForSelector('#enter-world:visible');
  assert.equal(await page.locator('#enter-world span').innerText(), 'Continue your journey');
  assert.equal(await page.locator('#char-creation').count(), 0);
  await page.click('#enter-world');
  await page.waitForSelector('[data-ready="true"]', { timeout: 180000 }); await page.waitForSelector('#loading', { state: 'detached' });
  assert.deepEqual((await inventory()).inventory, beforeReload.inventory); assert.deepEqual((await inventory()).cargo, beforeReload.cargo);
  assert((await character())?.name === hero.name);
  await wait(() => window.__astra.getState().story.phase === 'exploration');
  assert.equal((await state()).mounted, false); assert.equal((await inventory()).gold, 0);
  console.log('✓ Reload preserves inventory, remaining cargo, open lids, location, and completed introduction');
  const wasLocked = await page.evaluate(() => { const locked = !!document.pointerLockElement; if (locked) document.exitPointerLock(); return locked; });
  if (wasLocked) { await page.waitForSelector('[data-kind="pause"]'); await page.click('[data-action="close"]'); }
  const yaw = (await state()).yaw;
  await page.mouse.move(490, 200); await page.mouse.down({ button: 'right' }); await page.mouse.move(555, 215, { steps: 4 }); await page.mouse.up({ button: 'right' });
  assert(Math.abs((await state()).yaw - yaw) > .05);
  await page.evaluate(() => { document.querySelector('#world-canvas').requestPointerLock = () => Promise.reject(new DOMException('Blocked by iframe', 'SecurityError')); });
  await page.mouse.click(490, 200); await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('Drag to look'));
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(500);
  await page.click('#inventory-toggle'); assert(await page.locator('[data-kind="inventory"]').isVisible()); assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.click('[data-action="close"]');
  console.log('✓ Embedded-preview drag fallback and the mobile inventory layout work');
  assert.deepEqual(errors, []); assert.deepEqual(failed, []);
  console.log('All chapter browser smoke tests passed.');
} catch (error) {
  console.log('Last state:', await state().catch(() => null));
  console.log('Last inventory:', await inventory().catch(() => null));
  throw error;
} finally { console.log('Uncaught browser errors:', errors); await browser.close(); }
